version: '3'
services:
  lb:
    build:
      context: .
    image: load-balancer
    container_name: load-balancer
    ports:
      - '3030:3030'
    command: --backends 'http://web1:3031,http://web2:3032,http://web3:3033'

  web1:
    image: strm/helloworld-http
    ports:
      - '3031:3031'

  web2:
    image: strm/helloworld-http
    ports:
      - '3032:3032'

  web3:
    image: strm/helloworld-http
    ports:
      - '3033:3033'
